name: Testes do Robot Framework

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Verificar diretório atual
      run: |
        run: pwd
